name: cmake-build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-22.04
        - os: macos-12
        - os: windows-2022

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
      with:
        path: bindiff

    - uses: actions/checkout@v4
      with:
        repository: google/binexport
        path: binexport

    - name: install ninja
      uses: turtlesec-no/get-ninja@1.1.0

    - name: enable dev cmd (windows)
      if: matrix.os == 'windows-2022'
      uses: ilammy/msvc-dev-cmd@v1.12.1

    - name: enable mold (linux)
      if: matrix.os == 'ubuntu-22.04'
      uses: rui314/setup-mold@v1

    - name: configure cmake
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: |
        mkdir -p ${{ runner.workspace }}/build
        cmake "${{ github.workspace }}/bindiff" -G Ninja \
          "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
          "-DBINEXPORT_ENABLE_IDA=OFF"

    - name: build
      working-directory: ${{ runner.workspace }}/build
      shell: bash
      run: cmake --build . --config "${BUILD_TYPE}"

    - name: upload artifacts
      uses: actions/upload-artifact@v3.1.2
      with:
        name: BinDiff-${{ runner.os }}
        path: |
          ${{ runner.workspace }}/build/bindiff
          ${{ runner.workspace }}/build/tools/bindiff*
